### ISSUE TITLE
Git workshop

### ISSUE THREAD

**Issue by bryanburgers** [sfdevs/meetups#1]
Another git workshop
## Things we need to make this talk happen
- [x] Speaker: @weierophinney @sclarson
- [x] Venue: Blend
- [x] Date: May 3, 2016
- [x] Get summary text from speaker
- [x] Create meetup.com event

**Comment by harmstyler** [comment]
@sclarson Blend can host this one on May 3.

**Comment by sclarson** [comment]
@weierophinney tentatively confirmed being able to make it.

You can steal summary text from the previous one.

**Comment by bryanburgers** [comment]
@sclarson @weierophinney @harmstyler Meetup event created. http://www.meetup.com/sfdevs/events/230630203/

**Comment by sclarson** [comment]
https://services.github.com/kit/downloads/github-git-cheat-sheet.pdf
