### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by bryanburgers** [sfdevs/meetups#13]
I would love to learn about Progressive Web Apps.

Some things that could be covered in a talk about this
- What are Progressive Web Apps
- Service Workers
- Push notifications
- Offline modes
- Compatibility
- How various browsers handle the "Install as an App" part
- What to do about browsers that don't support some of the features

**Comment by dblackker** [comment]
I'm interested in talking about this.

**Comment by aligneddev** [comment]
I'm interested in learning and hearing more about this!

**Comment by zedfoxus** [comment]
I'm very interested and hope I can make it to this session. I'd vote for you to talk about it, @bryanburgers

**Comment by bryanburgers** [comment]
Having never written a PWA, I'm definitely OK with allowing @dblackker to take this one.

**Comment by harmstyler** [comment]
Blend could host, but lately we've been at capacity when Blend is hosting. @sclarson / @bryanburgers / @Kwen any idea if Raven could act as Venue?

**Comment by zedfoxus** [comment]
Sorry @dblackker, I missed your comment prior to recommending Bryan to speak. Would love to hear you speak, and thanks for volunteering!

**Comment by jxn** [comment]
@dblackker If you'd be ready, I'd suggest we try to do this on May 23 or May 30.  If you have another preferred date in mind, yell.  As @harmstyler said, Blend would host, but we'd probably prefer a larger venue if we can get one.  Blend _might_ also be able to host at the Design Center, but it's still a little cramped there.

**Comment by Kwen** [comment]
Raven should be able to host, assuming @bryanburgers / @sclarson / @daniames  will be around to turn off the lights and lock up. (I'm coaching my son's baseball team on Tuesdays all of May/June.)

**Comment by danitornow** [comment]
I can definitely stay and lock up! :100:

**Comment by sclarson** [comment]
I should also be available either of those days for opening/lockup
purposes.

**Comment by dblackker** [comment]
@jxn I can be ready for the 23rd / 30th, those dates work for me.

**Comment by Kwen** [comment]
Raven Training Center is free on the 30th. There's an "all-day" event on the 23rd that I'm assuming really only runs from 8-5, but I'd have to double-check that.

**Comment by harmstyler** [comment]
30th then? just to play it safe?

**Comment by Kwen** [comment]
Ok, Raven Training Center is reserved for the 30th. (I should be able to get approval for food/pop again.)

**Comment by harmstyler** [comment]
@jxn will create the meetup event when event details are in hand.

**Comment by sclarson** [comment]
@dblackker Have a title/abstract you want for this or should I have @jxn make one up when he posts it? :)

**Comment by dblackker** [comment]
@sclarson I just sent him some info 👍

**Comment by jxn** [comment]
The event is up; announcement to follow.  https://www.meetup.com/sfdevs/events/239637490/

**Comment by harmstyler** [comment]
Confirmed the meetup is available. Closing this issue.
