### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by Gagege** [sfdevs/meetups#16]
I've been using [React Native](http://facebook.github.io/react-native/) on and off for the past year. Now I'm pretty much doing it full time. I'd be interested in presenting it at the end of November or later. It's a great cross-platform framework that I think mobile developers would be interested in.

**Comment by jxn** [comment]
👍 I dig it.  November is CodeCamp month, so I'm not sure that we'll have a meet up (if you want to try giving this at CodeCamp there may still be time).  Otherwise, perhaps late november or early december?

**Comment by weierophinney** [comment]
I think December would be fantastic; could even have a get-together afterwards as a sort of holiday party.

**Comment by Gagege** [comment]
@jxn Yeah, December would be best for me, too. I'm going to be really busy at the beginning of November and will probably need a break!

**Comment by jxn** [comment]
@Gagege are you still up for doing this in December?  Maybe the 1st or 2nd Tuesday?

**Comment by Gagege** [comment]
@jxn Did you get my reply via email? It's not showing up here for some reason.

Anyway, yes. Still on for the 2nd Tuesday.

**Comment by sclarson** [comment]
Still using react native a lot @Gagege or more on Kotlin these days?  I'd be interested in doing a follow up on the former or something new on the latter in the coming months if you're interested.

**Comment by Gagege** [comment]
I haven't been keeping up with React Native at all since January. But, I'd be happy to talk about Kotlin (and Android maybe?) since that's been my only focus for the past few months.

**Comment by harmstyler** [comment]
Looks like we forgot to close this one. https://www.meetup.com/sfdevs/events/235767551/
