### ISSUE TITLE
Docker - 100 level intro

### ISSUE THREAD

**Issue by sclarson** [sfdevs/meetups#18]
I would love to learn about Docker.

Some things that could be covered in a talk about this
- What Docker is in different contexts ( Linux, Unix, ...maybe Windows)
- Using docker-compose to build development environments
- What kinds of things are sped up by Docker.

@robertjacobson you could probably get a great idea of scope based on @bphogan's Docker Dev Environments talk but you're skipping TCCC today :p

**Comment by robertjacobson** [comment]
XD that was my plan. I'll look forward to the slides being published.
