### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by aligneddev** [sfdevs/meetups#19]
I would love to learn about GraphQL. I've been hearing about it onhttps://www.netlify.com/blog/2017/05/11/staying-cool-with-graphcool/ and other articles. It looks like it can be very useful.

http://graphql.org

Some things that could be covered in a talk about this
- What it is
- How it's better than rest
- Backend implementation (.Net https://github.com/graphql-dotnet/graphql-dotnet/issues/338, PHP, etc)
- services (graphql)
- Demo app with Github or created API

-----

- [x] Speaker: @bkegley
- [x] Venue: Raven Training Center
- [x] Date: July 23rd
- [x] Get summary text from speaker
- [x] Create meetup.com event

**Comment by bryanburgers** [comment]
Potential advanced topic: strategies to prevent `n+1` queries when building a GraphQL endpoint.

**Comment by bkegley** [comment]
I'd love to give an overview of GraphQL! I've been using it to manage internal operations at Coffea for about a year and have grown to be a pretty big proponent of it.

All of my implementation is in JavaScript (Node and React) but an overview would transcend any specific language implementation.

I don't think Coffea would have a space that would allow us to host so we'd have to find another venue. Let me know the best way to go from here to get this rolling.

**Comment by harmstyler** [comment]
@bkegley that sounds great. Could you write up an abstract (a paragraph or two) and add it as a comment here? After that we'll find a date/venue that will work for everyone.

**Comment by aligneddev** [comment]
Thanks for volunteering! I've been wanting to learn more about GraphQL and have read some. Would you be able to talk about the server side of things too? I think I have a grasp on the client side, but how the server stitches things together is still a mystery to me.

**Comment by Kwen** [comment]
Great topic. I'll take care of getting Raven reserved to host it. @bkegley is there a Tuesday night in July (or August) that would work best for you, schedule-wise? (Training Center is already in use July 16th & August 13th. Any other Tuesday in July/August we can get it.)

**Comment by bkegley** [comment]
*Abstract*
GraphQL is growing rapidly in popularity as an alternative to REST. But, what is GraphQL and what differentiates it from REST? What benefits does it offer for both the user and developer?

Over the course of the talk we'll be diving into the world of GraphQL covering advantages and difficulties of developing a GraphQL API. From a starting point of defining new vocabulary in use with GraphQL we'll advance to more difficult topics such as pagination, authentication and schema stitching. Come prepared for real-life use cases that GraphQL works to solve and possibly an open mind to reconsider REST.

@Kwen let's do July 23rd!

@aligneddev we'll definitely talk through that and integrating existing REST APIs into a GraphQL schema. Anything else that'd be helpful?

**Comment by harmstyler** [comment]
@Kwen, I'm not listed as an organizer on meetup.com, so I can't create the event. Are you able to?

**Comment by Kwen** [comment]
Posted it. https://www.meetup.com/sfdevs/events/262809318/ @bkegley take a look and let me know if you want any tweaks made. Once I get the thumbs up, I'll announce it.

**Comment by Kwen** [comment]
@bkegley What's your meetup profile, so I can make you presenter before I announce it?

**Comment by Kwen** [comment]
Nevermind! Found ya.

**Comment by Kwen** [comment]
Announcement sent.

**Comment by bkegley** [comment]
Looks great! Thanks for putting it together
