### ISSUE TITLE
Blockchain - Explanation and application

### ISSUE THREAD

**Issue by dblackker** [sfdevs/meetups#21]
I would love to talk about blockchain technology.

Some things that could be covered in a talk about this
- What is blockchain technology?
- How does it work and what applications exist?
- As a developer, how do I get started implementing my own blockchain?

Blockchain, the underlying technology in cryptocurrency is all the hype right now with some cryptocurrency values skyrocketing over 1500% last year! Let's discuss how blockchain works and how it is useful in markets beyond cryptocurrency. Learn how to get started implementing your own blockchain!

"Email is to the internet as cryptocurrency is to the blockchain."

-----

- [x] Speaker: @dblackker 
- [x] Venue: Carsforsale.com
- [x] Date: January 30, 2018
- [x] Get summary text from speaker
- [x] Create meetup.com event

**Comment by dellintosh** [comment]
Great big 👍 !

**Comment by dblackker** [comment]
Possibility that Carsforsale.com could host. I'll find out more today.

**Comment by dblackker** [comment]
@bryanburgers - Is Jan 30th too soon as far as notice goes? I confirmed that Carsforsale can host.

**Comment by harmstyler** [comment]
@sclarson can you create the meetup.com event? 
@dblackker can you get us a summary, or are you good with the summary provided in this issue?

**Comment by dblackker** [comment]
That summary is OK, tweak as you see fit.

**Comment by sclarson** [comment]
@dblackker https://www.meetup.com/sfdevs/events/246909966/

Do those details look correct?
