### ISSUE TITLE
Mesos/Marathon

### ISSUE THREAD

**Issue by dan-akkerman** [sfdevs/meetups#22]
I would love to learn about... I wish somebody would give a talk about that.

Some things that could be covered in a talk about this
- A brief introduction of the presenters, the company they represent, and an overview of the presentation
- Use of Apache Mesos to manage a computer cluster, and its counterpart Marathon, which is a container orchestrator
- An overview of the capabilities of both to create a framework to enable a large scale processing capability using Docker containers
- An overview of the use of ELK Stack (Elasticsearch, Logstash, and Kibana; now called the Elastic Stack) as a mechanism to track the container processing and identify job failures
- A background and overview of all three technologies and how they're used as the solution to a problem
- A brief, reduced demonstration
- A Q&A discussion at the end of the presentation and demo

**Comment by bryanburgers** [comment]
That's a very specific outline! Would you also like to **give** this talk? Because that would be awesome.

**Comment by Kwen** [comment]
I've got the Raven Training Center reserved for March 6th, so we are covered on venue & date.

**Comment by dan-akkerman** [comment]
Sounds good -- thanks for setting this up.

Dan

Sent from BlueMail<http://www.bluemail.me/r?b=12095>
On Feb 16, 2018, at 9:17 AM, Kwen <notifications@github.com<mailto:notifications@github.com>> wrote:

I've got the Raven Training Center reserved for March 6th, so we are covered on venue & date.
