### ISSUE TITLE
Introduction to NodeJS, and N|Solid the NodeJS Runtime

### ISSUE THREAD

**Issue by dmikey** [sfdevs/meetups#25]
I would like to come give a presentation that would like be the first is a series of presentations and workshops around NodeJS. 

This talk will be introductory as a whole to NodeJS. 

* What it is
* How it works
* What we can use it for

And then we'll pivot to introduce N|Solid (disclaimer I work for NodeSource, the company behind N|Solid)

* What is N|Solid
* Why we want it
* How it works
* How do we use it

Final

And a general discussion around the current state of NodeJS in the industry.

Thanks!

**Comment by bryanburgers** [comment]
@dmikey Awesome! It looks like you're located in San Jose. This is a meetup that occurs in Sioux Falls, South Dakota (not San Francisco). Are you volunteering to come to (the other) SF to give this talk?

**Comment by dmikey** [comment]
@bryanburgers my bad! I need to update that, I've since relocated to Yankton! I'll be driving up :)

**Comment by bryanburgers** [comment]
@dmikey Well great to hear! I just wanted to verify that it wasn't a case of mistaken location before we invest time into getting everything set up.

**Comment by harmstyler** [comment]
@dmikey thanks for the talk submission. Would some time in mid-September fit your schedule?

**Comment by dmikey** [comment]
Sorry folks had some things mess up this month, Nodesource liquidated, so I wont be covering those portions :) but can still do some awesome NodeJS stuff. Totally available!

**Comment by harmstyler** [comment]
closing this as the intro talk was given at Code Camp. 
@dmikey we'd love to have you back in Sioux Falls again, so if you ever want to give another talk, hit us up!
