### ISSUE TITLE
[PROPOSAL]: Fundamentals of networking for web developers

### ISSUE THREAD

**Issue by hrkeni** [sfdevs/meetups#26]
**Title**: Fundamentals of networking for web developers

**Description**
We have all used the internet. Some of us might even have written code for a web site. Now let's demystify how it all works. Things to be covered:
- Basics of networking and networking tools
- How do domain names and addresses work
- Network structure and topology
- Protocols, layers, and packets
- Network factors affecting web reliability and performance
- The future of web networks

The outline and topics for discussion are a work in progress and I might focus on something more specific or split this into multiple parts if necessary.

-----

- [x] Speaker: @hrkeni
- [x] Venue: CarsForSale.com
- [x] Date: Feb 18, 2020
- [x] Create meetup.com event

**Comment by harmstyler** [comment]
Shooting for Feb 11, 2020 at CarsForSale

**Comment by harmstyler** [comment]
@hrkeni can we get a copy of the video from the event?
