### ISSUE TITLE
[PROPOSAL]: React + TypeScript at Prismatic

### ISSUE THREAD

**Issue by hipplej** [sfdevs/meetups#27]
**Title**: React + TypeScript at Prismatic

**Description**
We use React and TypeScript quite heavily at Prismatic. We've got a fairly large and non-trivial application running in production, and we're constantly adding new features, fixing bugs, and refactoring old designs. In this talk we'll explore some of the ways that using React with TypeScript has made this a productive and enjoyable experience.

Our lead Front-End Architect, Adrian Carriger, has several years of experience using both and has agreed to give a presentation in the coming weeks for anyone who is interested.

**Requested Location**
Zoom would be preferable, but Teams would also be fine.

**Time**
Sometime after March 15th. If someone could run down what times people would prefer and let me know, that would be great.

**Comment by aligneddev** [comment]
this sounds really good to me. Especially with the experience and non-trivial parts.
I realized that I know Adrian, but haven't seen him for a year. :-)

**Comment by harmstyler** [comment]
Zoom would work fine. No need for a venue.

We generally schedule a month out, but it's been a while since our last meetup, so we'll probably make any time work.

**Comment by awayken** [comment]
I'm not exactly sure how this process works. Are you looking for people to chime in times that work for them?

**Comment by harmstyler** [comment]
> I'm not exactly sure how this process works. Are you looking for people to chime in times that work for them?

Mostly, we want the speaker to have a say in scheduling.

**Comment by awayken** [comment]
> > I'm not exactly sure how this process works. Are you looking for people to chime in times that work for them?
> 
> Mostly, we want the speaker to have a say in scheduling.

Yeah, that actually makes sense. Let's go with that.

**Comment by harmstyler** [comment]
Event is live. Prismatic is using their Zoom account. Think we're good here.
