### ISSUE TITLE
Docker and/or Kubernetes

### ISSUE THREAD

**Issue by tlarnold10** [sfdevs/meetups#28]
**Subject:** Docker and/or Kubernetes

TODO: ACTUAL DESCRIPTION NEEDED

I would love to learn about Docker and Kubernetes. I wish somebody would give a talk about that.

Some things that could be covered in a talk about this
- Differences between Docker and Kubernetes.
- Moving current environment to Docker. 
- Multi-cloud Kubernetes clusters
- Microservices in Kubernetes

----

- [x]  Speaker: @arahja
- [x]  Venue: Omnitech Inc. 
- [x]  Date: March 9, 2023
- [x]  Get summary text from speaker
- [x]  Create meetup.com event

**Comment by taylorreece** [comment]
I'd be glad to present on what I learned when I was consulting and rolling out a mutli-cloud service mesh using https://istio.io/ on top of Kubernetes.  I'm wrangling two kids under 4 right now, but will do my best to get a presentation together and give everyone a couple week's heads' up before presenting.

Maybe we could do a lunch-and-learn thing online one day?

**Comment by aligneddev** [comment]
Great idea @tlarnold10. Thanks for being willing to share, @taylorreece . I'm looking forward to hearing this. The lunch-and-learn style worked well the last time with Adrian and Typescript

**Comment by paulbenjamin3409** [comment]
Agree with @aligneddev, I would love to see this presentation as well.

**Comment by tlarnold10** [comment]
Sounds great, looking forward to it!

**Comment by harmstyler** [comment]
@taylorreece any chance you've made progress on this?

**Comment by taylorreece** [comment]
@harmstyler I've not :-(. It's definitely something I want to do one of these days, but kids and work have been eating most of my free time.

**Comment by tlarnold10** [comment]
@taylorreece classic kids and work... always weighing people down...

**Comment by hrkeni** [comment]
@taylorreece I'd be happy to speak or collaborate with you on something related to Docker and/or k8s if there is still any interest. We've built our whole backend on resolve.com with kubernetes/microservices and it has been a fantastic experience for us. I would be happy to share some knowledge here.
@arahja

**Comment by arahja** [comment]
I gave an internal presentation on docker/kubernetes to people at Resolve. I could modify it and present if you want as well.

**Comment by taylorreece** [comment]
@hrkeni @arahja at this point, I bet you two would be better suited than I to give a Docker/K8s talk. I don't have a direct hand in our Docker usage and Prismatic, and haven't done much with K8s in two years now.

**Comment by aligneddev** [comment]
I could give a presentation on a following get together after this about different ways to run Containers in Azure, focusing on Azure App Containers. I was able to do some research and have an article up https://aligneddev.net/blog/2022/azure-app-containers/

**Comment by hrkeni** [comment]
@aligneddev That's fantastic. I would recommend that for a lot of projects. The only reason we didn't use it was because it wasn't GA yet. This area is vast and has many options between all the cloud providers' products and CNCF projects, so we can try to present a series of talks that complement each other. I'm certainly open to collaboration here.

I also think a talk about DDD and how that plays into designing software for microservices and the tradeoffs of those design decisions. Just need a gauge of interest levels for something like that, and how it can fit into other presentations.

**Comment by aligneddev** [comment]
@hrkeni or @arahja now that we have an October event scheduled, are you interested in talking about Docker/K8s in November or December? I think it'd be great to be able to have one every month for awhile.

I've been learning a lot about DDD and am thinking about that for a presentation myself (or Containers in Azure is another option)

**Comment by arahja** [comment]
I have given an internal presentation on docker/k8s. I could polish up the presentation for this group if you want.

**Comment by sclarson** [comment]
Sounds good to me. Where do we want to do it?

**Comment by aligneddev** [comment]
@arahja do you work somewhere that would be willing to host it?
Otherwise we can help find a place

**Comment by paulbenjamin3409** [comment]
@aligneddev @arahja the library has meeting rooms with projectors which we can use.  I can call and whats available, if needed. Please let me know.

**Comment by arahja** [comment]
@aligneddev @paulbenjamin3409 I work remotely, so I do not have a place off hand where my company could host.

**Comment by aligneddev** [comment]
I'll ask around for a hosting location. The library still seems like a good option, but I'll ask first.

@arahja, we'd need a short description about you and a title with a description about the presentation.
Do you have some evenings 5:30 to 7 that would work for you in November (I have something the 14th, but besides Thanksgiving I don't have set plans)? Maybe Monday, Tuesday or Thursday?

**Comment by Kwen** [comment]
Hosting at Raven Industries is always an option!

**Comment by aligneddev** [comment]
Hi @arahja, I'm just checking in if you're up for giving your presentation in November. 
@Kwen I think it'd be great to have it at Raven

**Comment by aligneddev** [comment]
@arahja It'd be great to hear back from you and what you think. Thanks!

**Comment by arahja** [comment]
Hey @aligneddev, I got a little busy this month. Could we push this presentation to early December?

**Comment by aligneddev** [comment]
No problems, @arahja. What are some days and times that work for you? Do you have an overview or description for the presentation?

If you give a few options, I can help find a location and we can get it scheduled or we have chatted about having a Saturday in February with a few sessions focused on containers. Yours would be a great way to start off the day.

**Comment by arahja** [comment]
My short and sweet overview of the presentation is this presentation which I named "Kubernetes 101" is the basics about docker and Kubernetes to understand the core concepts of the system and what it does.

I am unavailable 12/6/22, 12/17/22, 12/18/22 and Christmas through new years. Other than that I can give the presentation at night or over a lunch or something like that. I am also available in February.

**Comment by aligneddev** [comment]
Thanks for your willingness to share. It looks like with Christmas and the holidays, that February is going to be the time. I'll work with others and give you more details as we have them. 

Thanks!

**Comment by aligneddev** [comment]
@arahja Sorry for the delay. I got word that we can use the Startup Sioux Falls building on a Saturday in March or April. March 4 and 11 will not work because of some maintenance planned on the building.
Does the 18th, 25th or April 1st work for you?
Your Kubernetes 101 with docker basics would kick-off the day 

Here's a rough idea of what the day could look like, but needs more input and planning
9 - introduction
9:15 to 10:15 Your presentation
10:15 to 12 - have a workshop time with smaller groups to build and run some containers as an introduction (need several group leaders to help those who get stuck) I'm sure we could find something on Github or from Microsoft Learn
people with more experience can help people without to get going
another option would be to let more experienced build something together using containers
12 to 1 lunch, chatting and talking
1 to 2 have a group discussion with some moderators to talk about experiences, how they are using containers, downsides, hosting in AWS/Azure

if you want to chat more, you can find me on the https://www.sfdevs.com/ Slack channel

**Comment by arahja** [comment]
@aligneddev 
March 18th, 25th, and April 1st should all work for me.
I don't have an email address that qualifies me for an account on the sfdevs.com slack channel. I have a gmail.com and resolve.com email address.

**Comment by aligneddev** [comment]
Thanks for responding!
I'll check and get back to you here.

Can you add a short description of what you'll talk about?

Could you send me an email at klogan@omnitech-inc.com? Just so we can communicate a little better.

**Comment by aligneddev** [comment]
I talked to some co-workers more (something I should have done earlier) and they pointed out it's hard to give up a Saturday morning, even if it is something to connect and learn together. Maybe someday we'll have a bigger event.

So I'm pivoting and simplifying.

Omnitech will host the event. Let's just have you present from 6 to 7, with open doors at 5:30.
@arahja give me a Monday or Thursday night that works for you and a summary to put on the Meetup event. I'll get it scheduled.

Thanks for your patience and bearing with my ideas!

**Comment by aligneddev** [comment]
This is scheduled for March 9th. https://www.meetup.com/sfdevs/events/291843337
@sclarson please mark as done
