### ISSUE TITLE
[PROPOSAL]: Clean Architecture and Domain Driven Development

### ISSUE THREAD

**Issue by aligneddev** [sfdevs/meetups#30]
**Title**: Clean Architecture and Domain Driven Development

**Description**
Discuss Clean Architecture ideas from Uncle Bob's book and add in Domain Modeling Made Functional from Scott Wlaschin sprinkling in DDD and functional.

This is an updated version from the talk John Townsend and I gave at SD Code Camp 2019. https://aligneddev.net/blog/2019/clean-architecture-software-presentation/

**Requested Location**
Omnitech

Probably for December 2022, unless I should do a follow up Azure App Containers after the Docker talk.
The other idea was to have a Saturday "SD Freeze" where DDD and architecture could be topics. DDD and Functional both need a lot more time than I could give it in this presentation

---

- [x]  Speaker: @zprobinson 
- [x]  Venue: Omnitech
- [x]  Date: Tuesday, March 26, 2024 5:30 PM 
- [x]  Get summary text from speaker
- [x]  Create meetup.com event

**Comment by aligneddev** [comment]
It's my fault for not committing to a date for this. This might be a good one for early May 2023 or August/Sept/Oct (I'm not keen on losing a nice warm evening outside :-) ). It just needs a bit of updating.

**Comment by zprobinson** [comment]
I'm very interested in this talk. I'm a big fan of Scott Wlaschin and Domain Modeling Made Functional and would love an event scheduled to discuss it.

@aligneddev, if you want some assistance polishing the presentation, I'd be happy to help in whatever way I can. I'd love to see this happen.

**Comment by aligneddev** [comment]
@zprobinson thanks for the feedback. It's always good to meet another Scott Wlaschin and DDD fan.

I actually gave this talk at [NE Code in July 2023](https://aligneddev.net/blog/2023/necode2023-clean-architecture-presentation/) and could brush it up a bit more and share it again. I'll ask in the Slack chat to gauge interest.

**Comment by harmstyler** [comment]
Event created https://www.meetup.com/sfdevs/events/299696164/
