### ISSUE TITLE
React vs Angular (vs Vue)

### ISSUE THREAD

**Issue by tlarnold10** [sfdevs/meetups#32]
**Title**: React vs Angular (vs Vue)

**Description**
Two of the most popular front end frameworks. Give a demo of an application developed in both frameworks. Talk about similarities, differences, and use cases for each. 

----

- [x]  Speaker: @tlarnold10 
- [x]  Venue: Blend Interactive @ 231 S Phillips Ave Ste 200, Sioux Falls, SD 57104
- [x]  Date: April 6th, 2023 @ 5:30
- [x]  Clean up summary for event page
- [x]  Create meetup.com event

**Comment by jxn** [comment]
@tlarnold10 You'd be speaking or was this an idea/request?

**Comment by tlarnold10** [comment]
I would be open to presenting on the topic.

**Comment by harmstyler** [comment]
@tlarnold10 did you have a date or venue preference?

**Comment by tlarnold10** [comment]
Date, wouldn't be for a couple months. Maybe around May?
Venue, I might be able to ask some old coworkers if Omnitech or CentralSquare would be open to housing such a meetup.

**Comment by aligneddev** [comment]
I'm sure we can host at Omnitech. Blend offered their space as well.
If you're up to it, it might be good just to choose a date and get it on the calendar.

**Comment by tlarnold10** [comment]
Thinking April or May. Need to see what my wife's work schedule is like before I can set a date.

**Comment by tlarnold10** [comment]
@aligneddev how about April 6th? Either at Omnitech or @harmstyler could see if I could do it at CST? Or any other volunteers. I might be able to swing something with Startup Sioux Falls as well.

**Comment by aligneddev** [comment]
April 6th is good. Let's see if we can find a different host, but Omnitech could be a backup.
I heard https://mybluepeak.com/sioux-falls-tech-hub/ would be willing to host for free. Blend, Market Beat, Cars For Sale, and Raven have been venues in the past. Someone suggested getting a library room as well. Could you or someone help nail that down?
I talked to Amos at Startup Sioux Falls and it seems that we'd need someone who's a member (subscription that works there) to sponsor us and possibly need to pay. They were still figuring it out.

**Comment by tlarnold10** [comment]
Let me see what I can do, I'll keep you posted.

**Comment by tlarnold10** [comment]
@aligneddev location and date updated in description.

**Comment by aligneddev** [comment]
https://www.meetup.com/sfdevs/events/292429192/
