### ISSUE TITLE
[PROPOSAL]: Game Jam Hosted by Blend Interactive

### ISSUE THREAD

**Issue by Nhawdge** [sfdevs/meetups#39]
**Title**:  Game Jam Hosted by Blend Interactive

**Description**
Hey all, a few of us at Blend will be participating in the [Mini Jame Gam 29](https://itch.io/jam/mini-jame-gam-29) on Friday April 12th. It will be from 9 am to about 5 pm or when people start wearing out. The game jam will provide a theme, and a special object for us to build around. This is announced when the jam starts.

This is our 3rd time doing a game jam. We plan to use a [home build engine](https://github.com/mrdrbob/2b2d) written in Typescript, based off of [Bevy](https://bevyengine.org/). We generally use [Aseprite](https://www.aseprite.org/) for art (it has animation integrations). For building levels, [LDTK](https://ldtk.io/). 

This is about how the day looks:

9-10 am - Review Theme/Object and brainstorm session.
10-10:30 - Figure out everyone's interested area of work. 
10:30-Noon - Everything all at once
Noon-1 - Lunch break
1-4pm - Working time
4-5pm - Distribution and bug fixes. 

If we get enough people we may split into separate teams. Please bring a laptop, and any additional tools you think would be helpful. For example, microphone for recording sounds, drawing pad or tablet for making art. 

ALL ARE WELCOME!

**Location** 

Blend Office, Downtown Sioux Falls 
Address: [231 S Phillips Ave Ste 200, Sioux Falls, SD 57104](https://www.google.com/maps/dir//blend+interactive+address/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x878eb5983ecd13db:0x7530ac3dbb9c573a?sa=X&ved=1t:3061&ictx=111)

**Comment by harmstyler** [comment]
Event Created https://www.meetup.com/sfdevs/events/299887363/
