### ISSUE TITLE
[PROPOSAL]: Introduction to rust and/or why use rust

### ISSUE THREAD

**Issue by tlarnold10** [sfdevs/meetups#41]
**Title**: Introduction to rust and/or why use rust

**Description**
Currently learning rust and planning to build my own little project with the language. Share what it was like and what I learned as someone who has never worked with a low level language before. 

**Requested Location**
Raven

**Date**
July 11, 2024

**meetup**

https://www.meetup.com/sfdevs/events/301756602/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link

**Comment by tlarnold10** [comment]
This might be a duplicate of #2. @bryanburgers you still interested?

**Comment by bryanburgers** [comment]
@tlarnold10  I’m not particularly interested and I like the idea of getting the opinions of people with fresh eyes! All yours!
