### ISSUE TITLE
[PROPOSAL]: Building a web app with F#, Elmish, and Vite

### ISSUE THREAD

**Issue by tw0po1nt** [sfdevs/meetups#42]
**Title**: Building a web app with F#, Elmish, and Vite

**Description** 
F# isn't just theoretically a great language. It also has great tooling, a vibrant community of open source developers, and is extremely fun to write. Contrary to some of the misconceptions about functional programming, it can be (and is!) used to build the sorts of applications we build every day - front-end web apps, backend APIs, even cross-platform mobile and desktop apps! Using functional programming principals and tools, we can build robust apps with fewer bugs that are a lot more fun to maintain - and having fun is a really important aspect of work-life balance. In this talk, we will build a frontend web app in F# from scratch. While F# might seem unfamiliar to you right now, you'll see me use some more familiar tooling - Vite! That's right, we can use all the fancy, modern front-end tooling we're beginning to depend on every day with F#. Come see what can be done with F#, and let your imagination run wild thinking about what it could be like to start adding it as another powerful tool in your toolbelt!

---

- [x]  Speaker: @tw0po1nt 
- [x]  Venue: Omnitech 
- [x]  Date: September 30 @ 5:30 pm
- [x]  Clean up summary for event page
- [x]  Create meetup.com event

**Comment by harmstyler** [comment]
@tw0po1nt do you have a date in mind? Is Omnitech ok hosting?

**Comment by tw0po1nt** [comment]
@harmstyler We just got the ok to host it at Omnitech. Our target date is September 30

**Comment by harmstyler** [comment]
OK, did you have a time as well? If so, I think we're safe to create the event.

**Comment by tw0po1nt** [comment]
5:30-7:30

**Comment by harmstyler** [comment]
Great, Can I also get a speaker bio from you @tw0po1nt?
