### ISSUE TITLE
WebAssembly intro

### ISSUE THREAD

**Issue by jxn** [sfdevs/meetups#6]
I would love to learn about WebAssembly.

Some thing that could be covered in a talk about this
- What's webassembly
- How does it relate to asm.js and other projects?
- Can I use it now?
- How big of a deal is it?
- Does it harm reverse-engineerability of the web?
- Does this mean client-side scripting is going to get harder?

**Comment by sclarson** [comment]
We did this Sept 2016 and never updated this :)
